""
"" Basic Setup
""

set nocompatible      " Use vim, no vi defaults
set number            " Show line numbers
"set relativenumber    " Show relative line numbers
set ruler             " Show line and column number
set encoding=utf-8    " Set default encoding to UTF-8
set showcmd
set background=dark
filetype plugin indent on

""
"" Status Line
""

set laststatus=2                           " always show the statusline
"set statusline=%2*[%n%H%M%R%W]%*\ %f\ %h%m%r%{fugitive#statusline()}%=%1*%y%*%*\ %-14.(%l,%c%V%)\ %P
set statusline=
set statusline+=%<
set statusline+=%2*[%n%H%M%R%W]%*\ 
set statusline+=%f\ 
set statusline+=%h%m%r
set statusline+=%=
set statusline+=%1*%y%*%*\ 
set statusline+=%-14.(%l,%c%V%)\ 
set statusline+=%P

""
"" Whitespace
""

set nowrap                        " don't wrap lines
set tabstop=2                     " a tab is two spaces
set shiftwidth=2                  " an autoindent (with <<) is two spaces
set expandtab                     " use spaces, not tabs
set list                          " Show invisible characters
set backspace=indent,eol,start    " backspace through everything in insert mode
"set softtabstop=2
"set columns=150
set smarttab
set smartindent

" List chars
set listchars=""                  " Reset the listchars
set listchars=tab:\ \             " a tab should display as "  ", trailing whitespace as "."
set listchars+=trail:.            " show trailing spaces as dots
set listchars+=extends:>          " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen
set listchars+=precedes:<         " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen

""
"" Searching
""

set hlsearch    " highlight matches
set incsearch   " incremental searching
set ignorecase  " searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter

""
"" Wild settings
""

" TODO: Investigate the precise meaning of these settings
" set wildmode=list:longest,list:full
set wildmenu
set wildmode=list:longest,full

" Disable output and VCS files
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem

" Disable archive files
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz

" Ignore bundler and sass cache
set wildignore+=*/vendor/gems/*,*/vendor/cache/*,*/.bundle/*,*/.sass-cache/*

" Disable temp and backup files
set wildignore+=*.swp,*~,._*

""
"" Misc
""
set showmatch
set matchtime=3

""
"" Backup and swap files
""

set backupdir=~/.vim/_backup//    " where to put backup files.
set directory=~/.vim/_temp//      " where to put swap files.

" split switching - ctrl+(h|j|k|l)
" http://vim.wikia.com/wiki/Switch_between_Vim_window_splits_easily
"set wmw=0
map <C-H> <C-W>h
map <C-J> <C-W>j
map <C-K> <C-W>k
map <C-L> <C-W>l
